// Lista de códigos y nombres
const invitados = {
  // Lista de códigos Novia
  "HD123": ["Humberto Perez", "Daniela Sanchez"],
  "DS104": ["Ramiro Sánchez", "Victoria Ruiz"],
  "DS287": ["Julián Puente", "Edith Sánchez","Israel Puente","Said Puente","Tiana Puente","David Puente"],
  "DS659": ["Daniel Castañeda", "Mónica Sánchez","Ivander Castañeda","Irvin Castañeda","Ivanna Castañeda"],
  "DS432": ["Mireya González"],
  "DS930": ["Denisse Ruiz"],
  "DS375": ["Félix Ruiz", "Mayra González"],
  "DS246": ["Fabián Ruiz", "Argelia Torres"],
  "DS801": ["Miguel Silva", "Ma. de la Luz Ruiz"],
  "DS593": ["Sergio Silva ", "Vanessa Rodríguez"],
  "DS127": ["Carlos Silva ", "1 Acompañante"],
  "DS864": ["Miguel Silva ", "Lupita Hernández"],
  "DS509": ["Nidia Ruiz"],
  "DS742": ["Rosario Hasing", "Nidia Leal"],
  "DS646": ["Jesús Leal", "1 Acompañante"],
  "DS318": ["Rolando Treviño", "Nancy Leal"],
  "DS690": ["Ramón Hernández", "Nallely Leal"],
  "DS451": ["Raúl Balderas", "Yolanda Ruiz"],
  "DS976": ["Isaias Balderas", "1 Acompañante"],
  "DS284": ["Carlos Gómez", "Marilú Balderas"],
  "DS735": ["Nelly Guerrero", "1 Acompañante"],
  "DS160": ["Evodio Cerda", "Gaby Imperial"],
  "DS827": ["Eric Cerda", "Karina Lara"],
  "DS394": ["Roberto Martínez", "Guadalupe Sánchez"],
  "DS612": ["Álvaro Sánchez", "Ana Jimenez"],
  "DS948": ["Álvaro Sánchez", "Alondra Vela"],
  "DS273": ["Elena Sánchez", "1 Acompañante"],
  "DS581": ["René Sánchez", "Estefany Hernández"],
  "DS706": ["Elizabeth Sánchez", "1 Acompañante"],
  "DS139": ["Vicente Sánchez", "1 Acompañante"],
  "DS865": ["Reynold Sánchez", "Sandra De Osio"],
  "DS420": ["Gerardo Sánchez", "Yolanda Llanes"],
  "DS997": ["Yolanda Sánchez", "1 Acompañante"],
  "DS254": ["Luisa Sánchez", "1 Acompañante"],
  "DS618": ["Elisa Martínez", "1 Acompañante"],
  "DS783": ["Mónica Martínez", "1 Acompañante"],
  "DS346": ["Sandra Sánchez", "1 Acompañante"],
  "DS905": ["Juvencio Puente", "Rosy Silva"],
  "DS172": ["Marlene Sánchez", "1 Acompañante"],
  "DS469": ["Javier Méndez", "Liliana Padilla"],
  "DS830": ["César Castellanos", "1 Acompañante"],
  "DS597": ["Mauricio Muñiz", "1 Acompañante"],
  "DS214": ["Mario Sosa", "1 Acompañante"],
  "DS768": ["Víctor Zapata", "Braulio Ochoa"],
  "DS381": ["Ammi Salinas", "1 Acompañante"],
  "DS654": ["Mayra Diaz", "1 Acompañante"],
  "DS920": ["Zulema Carranco", "1 Acompañante"],
  "DS147": ["Kassandra Moreno", "1 Acompañante"],
  "DS589": ["Sharon Izaguirre", "1 Acompañante"],
  "DS702": ["Cinthia Morales", "1 Acompañante"],
  "DS336": ["Melissa Ibarra", "1 Acompañante"],
  "DS861": ["Ana Benavides", "1 Acompañante"],
  "DS495": ["Sandra Olalde", "Rubén Rodríguez"],
  "DS178": ["Evelyn Gamez", "1 Acompañante"],
  "DS924": ["Sofia Santiago", "1 Acompañante"],
  "DS607": ["Kevin Moncada", "Aylin Medellin"],
  "DS259": ["Sebastián Cervantes", "1 Acompañante"],
  "DS713": ["Daniela Vazquez", "1 Acompañante"],
  "DS384": ["Paola Nuñez", "1 Acompañante"],
  "DS950": ["Sergio Garcia", "Vanessa Garcia"],
  "DS526": ["Daniel Tovar", "1 Acompañante"],
  // Lista de códigos Novio
  "HP010": ["Enedelia Barajas"],
  "HP019": ["Ma. Elena Martínez"],
  "HP058": ["Alberto Garza", "Karina Pérez", "Alberto Garza", "Lilian Garza"],
  "HP091": ["Alejandro Rodríguez", "Marlene Pérez", "Andree González"],
  "HP115": ["Verónica Obregón", "Jaime Estrada"],
  "HP163": ["Noé Cardenas", "1 Acompañante"],
  "HP198": ["Héctor Obregón", "Xochitl Gomez"],
  "HP221": ["Rosy Martínez", "1 Acompañante"],
  "HP257": ["Enrique Obregón", "Francis Hidalgo"],
  "HP268": ["Paula Martínez", "1 Acompañante"],
  "HP305": ["Reynol Villarreal", "Janeth Cruz"],
  "HP329": ["Sergio Muñiz", "Ivette Escamilla"],
  "HP358": ["Andrés Vazquez", "Katia Salas"],
  "HP407": ["Gustavo Hernández", "Michelle Martínez"],
  "HP446": ["Mauricio Garza", "Sra de Garza"],
  "HP478": ["Aarón Ruiz", "Sandra Garcia"],
  "HP522": ["Diego Oropeza", "1 Acompañante"],
  "HP547": ["Louis Oropeza", "1 Acompañante"],
  "HP632": ["Oscar Ramírez", "1 Acompañante"],
  "HP671": ["Daniel Rodríguez", "Elizabeth Martínez"],
  "HP799": ["Daniel Moreno", "Isa Lara"],
  "HP888": ["Iván Fragoso", "Yisell Guerrero"],
  "HP934": ["Félix Morado", "1 Acompañante"],
};
